### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by pniau7** [holgern/pyRdatasets#1]
I'm getting the following error when pip installing rdatasets `ModuleNotFoundError: No module named 'imp'`

I'm using Python 3.12. Looking around for similar issues, I found that the 'imp' module was [deprecated](https://stackoverflow.com/questions/77401730/modulenotfounderror-no-module-named-imp).

Thanks for you module, and I hope to be able to use it in the future.

**Comment by holgern** [comment]
Can you try again? It should be fixed in the latest release.

**Comment by holgern** [comment]
The wheels before 0.2.8 are broken, please try again when you have installed an version < 0.2.8

**Comment by holgern** [comment]
The package is now also on conda-forge:
 https://anaconda.org/conda-forge/rdatasets/badges
